#!/bin/bash

# Check for CAP_NET_ADMIN
if ! iptables -nL &> /dev/null; then
  >&2 echo 'Container requires CAP_NET_ADMIN, add using `--cap-add NET_ADMIN`.'
  exit 1
fi

# Ensure that the container only has eth0 and lo to start with
for interface in $(ip link show | awk '/^[0-9]*:/ {print $2}' | sed -e 's/:$//' -e 's/@.*$//'); do
  if [ "$interface" != "lo" ] && [ "$interface" != "eth0" ]; then
    >&2 echo 'Container should only have the `eth0` and `lo` interfaces'
    >&2 echo 'Additional interfaces should only be added once tor has been started'
    >&2 echo 'Killing to avoid accidental clobbering'
    exit 1
  fi
done

cat <<EOT > /etc/torrc
VirtualAddrNetworkIPv4 10.192.0.0/10
AutomapHostsOnResolve 1
TransPort 0.0.0.0:9040 IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort
DNSPort 0.0.0.0:5353
SocksPort 0.0.0.0:9050
EOT

chown tor:tor /etc/torrc

iptables-restore /tmp/iptables.rules

echo "nameserver 127.0.0.1" > /etc/resolv.conf

su tor -c "$@"
